import Vue from 'vue'
import { Button, Tabbar, TabbarItem, Search, Icon, Swipe, SwipeItem, Image as VanImage, NavBar, Form, Field, Tab, Tabs, Sticky, DropdownMenu, DropdownItem, Picker, Popup, IndexBar, IndexAnchor, Cell } from 'vant'
Vue.use(Cell)
Vue.use(IndexBar)
Vue.use(IndexAnchor)
Vue.use(Popup)
Vue.use(Picker)
Vue.use(DropdownMenu)
Vue.use(DropdownItem)
Vue.use(Sticky)
Vue.use(Tabs)
Vue.use(Tab)
Vue.use(Form)
Vue.use(Field)
Vue.use(NavBar)
Vue.use(VanImage)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Icon)
Vue.use(Search)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(Button)
